version: "3.9"

# Use this for local development: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
services:
  api:
    build:
      target: deps
    command: pnpm dev
    volumes:
      - ./fymail-api/src:/app/src:ro
    environment:
      NODE_ENV: development

  web:
    build:
      target: deps
    command: pnpm dev
    volumes:
      - ./fymail-web/app:/app/app:ro
      - ./fymail-web/components:/app/components:ro
      - ./fymail-web/lib:/app/lib:ro
    environment:
      NODE_ENV: development
